services:
  consul:
    image: hashicorp/consul:1.15
    container_name: quietchatter-consul
    restart: always
    volumes:
      - ./consul_data:/consul/data
      - ./consul_config:/consul/config
    environment:
      CONSUL_BIND_INTERFACE: eth0
      CONSUL_CLIENT_INTERFACE: eth0
    command: "agent -server -bootstrap-expect=1 -ui -client=0.0.0.0 -data-dir=/consul/data -config-dir=/consul/config"
    network_mode: host
